application: plopquiz
version: 5-02
runtime: python
api_version: 1

default_expiration: "4d 5h"

handlers:



# dev handlers

- url: /console/static
  static_dir: console/app/view/static
  
# widget source
- url: /js/quiz/files/
  static_dir: static/widget/


  
- url: /console.*
  script: console/app/console.py
  login: admin

  
- url: /gaeutilities/css
  static_dir: utils/appengine_utilities/interface/css

- url: /gaeutilities/.*
  script: utils/appengine_utilities/interface/main.py
  login: admin
  
  
  
  
  
  
  
  # resource handlers
### Temporarily, unstatic files are being kept in the static folder ###

#- url: /static/scripts.*              
#  script: utils/js/javascript.py

#- url: /static/stylesheets/
#  static_dir: static/stylesheets/


- url: /static/stylesheets/img/
  static_dir: static/stylesheets/img/
  


- url: /static/beehold/
  static_dir: static/beehold/

- url: /static/html/       # this could go in stylesheets/img
  static_dir: static/html/


- url: /favicon.ico
  static_files: static/stylesheets/img/favicon.ico
  upload: static/stylesheets/img/favicon.ico


- url: /robots.txt
  static_files: static/utils/robots.txt
  upload: static/utils/robots.txt

- url: /sitemap.xml
  static_files: static/utils/sitemap.xml
  upload: static/utils/sitemap.xml




#### MAIN HANDLER ###
    
- url: /.*
  script: main.py



