application: plopquiz
version: 5
runtime: python
api_version: 1

handlers:

- url: /static/
  static_dir: static/



- url: /load
  script: /dev/loader.py

  
  
- url: /.*
  script: main.py


- url: /favicon.ico
  static_files: static/stylesheets/img/favicon.ico
  upload: static/stylesheets/img/favicon.ico


- url: /admin/.*
  script: ../ext/admin
  login: admin






