application: plopquiz
version: 7
runtime: python
api_version: 1

# todo: set static file expiration.... default_expiration: "4d 5h"


handlers:

# dev handlers

- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py
  login: admin

  
  
- url: /gaeutilities/css

  static_dir: utils/appengine_utilities/interface/css

- url: /gaeutilities/.*

  script: utils/appengine_utilities/interface/main.py

  login: admin
  
  # resource handlers

- url: /static/scripts.*              
  script: utils/js/javascript.py

- url: /static/stylesheets/
  static_dir: static/stylesheets/

- url: /static/beehold/
  static_dir: static/beehold/

- url: /static/html/       # this could go in stylesheets/img
  static_dir: static/html/



# MAIN HANDLER


- url: /.*
  script: main.py


- url: /favicon.ico
  static_files: static/stylesheets/img/favicon.ico
  upload: static/stylesheets/img/favicon.ico


